### ISSUE TITLE
Finish Meta Keys

### ISSUE THREAD

**Issue by RyanThompson** [anomalylabs/streams#53]
Create a small system to define `__created_at` and other meta key names.

**Comment by RyanThompson** [comment]
- [x] key_name
- [ ] created_at_name
- [ ] updated_at_name
- [ ] created_by_name
- [ ] updated_by_name

**Comment by RyanThompson** [comment]
Stuff them in config

**Comment by RyanThompson** [comment]
This feels like a keymap to me. That could also be used for name -> name_en translation/transformation.

**Comment by RyanThompson** [comment]
How do we handle these kinds of things..

**Comment by RyanThompson** [comment]
This needs to use the observer probably.
